platzigram/urls.py
from django.contrib import admin
from django.urls import path, include



# Import para hacer el hack de ver las imagenes desde el admin
from django.conf.urls.static import static
from django.conf import settings

'''Lo que hace es: Le suma a urlpatterns  una URL estatica con el valor de la media que tenemos y donde estamos parados en la media'''

# from django.http import HttpResponse
# funcion que sirve como vista, migraremos la funcion a un archivo views
# def hello_world (request):
#     return HttpResponse('Hello-wold!')
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello-world/', local_views.hello_world, name='hello_world'),

    # Con esta vista le mandamos un variable  de tipo GET como parametro que esta dentro del objeto request
    # path('sorted/', local_views.sorted_numbers,name='sort'),

    # Mandamos 2 variables diferentes valores fuera del objeto request, para crear la vista se deben colocar los parametros de entrada del request, name y la edad por separado
    # path('hi1/<str:name>/<int:edad>/', local_views.hi),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace = 'users')),

   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Este es una extension para que podamos ver las imagenes guardadas desde el admin:
# el Media_Url: indica la path en el caso que fuera un archivo
# El Media_Root: Es una ruta que le damos para que nos los guarde los archivos, aparte de los que ya tienen 

posts/urls.py
"""Post Urls"""
# Django
from django.urls import path

# Views
from posts import views
urlpatterns =[
    # Paths que estan relacionados con los posts
    path(route='',view=views.PostsFeedView.as_view(),name='feed'),
    # path('posts/new/', views.create_post, name='create'), 
    path('posts/new/',view=views.CreatePostView.as_view(),name='create'),
    path(route='posts/<int:pk>/',view=views.PostDetailView.as_view(),name='detail'),
    # tienes 2 formas de crear un path, colocando los nombres de cada variable que envias, o no colando ningun nombre de variable en la ruta y la vista. Tú eliges
]

users/urls.py
"""User Urls"""

# Django
from django.urls import path

# importacion para usar las vistas basadas en clases
from django.views.generic import TemplateView

# Views
from users import views

urlpatterns=[
   
         # Paths que estan relacionados con los users 
    # path(route='logout/', view=views.logout_view, name='logout'),  
    path(route='logout/', view=views.LogoutView.as_view(), name='logout'),
      # path(route='login/' ,view=views.login_view, name='login'),
    path(route='login/' ,view=views.LoginView.as_view(), name='login'),
    # path(route='me/profile/', view=views.update_profile, name='update'),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update'), # NOTA: Cuando tengas path con funciones y clases al mismo tiempo, asegurate de colocar primero las que son con funciones. De otro modo solo reconocera la de ClassViews y no las de funciones
     # primera vista basada en clases, que sera el detalle de un user

    # path(route='signup/', view=views.signup, name='signup'),    
    path(route='signup/', view=views.SignupView.as_view(), name='signup'),
   
    path(route='<str:username>/',view=views.UserDetailView.as_view(), name='detail'),
    # path(route='<str:username>/',view=TemplateView.as_view(template_name='users/detail.html'), name='detail'),

]

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head_content %}{% endblock %}
    <!-- <title>Document</title> Este parte de codigo sera generado por las aplicaciones -->

    {% load static %}
    <!-- este metodo genera los archivos estaticos que tenemos y busca a cual pertenece cada llamado -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{%static 'css/main.css' %}" />

</head>
<body>
    <!-- Este parte de codigo estara en otro archivo .html lo llamamos con el include -->
    {% include "nav.html" %}
    <div class="container mt-5">
        {% block container %} 
        {% endblock %}
    </div>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static 'img/instagram.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                        <img src="{{request.user.profile.picture.url}}" height="35" class="d-inline-block align-top rounded-circle"/> 
                        <!-- cada vez que tiens una variable que vincula un archivo colocamos al final el .url                        -->
                        {% else %}
                        <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>                        
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %} <!--Si no es la primera paginacion se mostrara este contenido-->
        <li class="page-item">
            <a href="?page={{page_obj.previous_page_number}}" class="page-link"> <!--Esto buscara la paginacion anterior que le corresponde sabiendo el numero de pagina en que se encuentra -->
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a href="#" class="page-link">
                {{ page_obj.number }} of {{page_obj.paginator.num_pages }} <!--Nos muestra el numero de pagina en el que estamos y el numero total de paginas-->
            </a>
        </li>
        {% if page_obj.has_next %} <!--Esto buscara si existe una paginacion despues de la actual-->
        <li class="page-item">
            <a href="?page={{page_obj.next_page_number }}" class="page-link"> <!--Busca si existe una paginacion siguiente para agregarle un enlace. Esto manda un argumento en la url con la variable "page" esta se igual al numero en que se escogio-->
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>