platzigram/urls.py
from django.contrib import admin
from django.urls import path, include



# Import para hacer el hack de ver las imagenes desde el admin
from django.conf.urls.static import static
from django.conf import settings

'''Lo que hace es: Le suma a urlpatterns  una URL estatica con el valor de la media que tenemos y donde estamos parados en la media'''

# from django.http import HttpResponse
# funcion que sirve como vista, migraremos la funcion a un archivo views
# def hello_world (request):
#     return HttpResponse('Hello-wold!')
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello-world/', local_views.hello_world, name='hello_world'),

    # Con esta vista le mandamos un variable  de tipo GET como parametro que esta dentro del objeto request
    # path('sorted/', local_views.sorted_numbers,name='sort'),

    # Mandamos 2 variables diferentes valores fuera del objeto request, para crear la vista se deben colocar los parametros de entrada del request, name y la edad por separado
    # path('hi1/<str:name>/<int:edad>/', local_views.hi),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace = 'users')),

   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Este es una extension para que podamos ver las imagenes guardadas desde el admin:
# el Media_Url: indica la path en el caso que fuera un archivo
# El Media_Root: Es una ruta que le damos para que nos los guarde los archivos, aparte de los que ya tienen 

posts/urls.py
"""Post Urls"""
# Django
from django.urls import path

# Views
from posts import views
urlpatterns =[
    # Paths que estan relacionados con los posts
    path(route='',view=views.PostsFeedView.as_view(),name='feed'),
    # path('posts/new/', views.create_post, name='create'), 
    path('posts/new/',view=views.CreatePostView.as_view(),name='create'),
    path(route='posts/<int:pk>/',view=views.PostDetailView.as_view(),name='detail'),
    # tienes 2 formas de crear un path, colocando los nombres de cada variable que envias, o no colando ningun nombre de variable en la ruta y la vista. Tú eliges
]

users/urls.py
"""User Urls"""

# Django
from django.urls import path

# importacion para usar las vistas basadas en clases
from django.views.generic import TemplateView

# Views
from users import views

urlpatterns=[
   
         # Paths que estan relacionados con los users 
    # path(route='logout/', view=views.logout_view, name='logout'),  
    path(route='logout/', view=views.LogoutView.as_view(), name='logout'),
      # path(route='login/' ,view=views.login_view, name='login'),
    path(route='login/' ,view=views.LoginView.as_view(), name='login'),
    # path(route='me/profile/', view=views.update_profile, name='update'),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update'), # NOTA: Cuando tengas path con funciones y clases al mismo tiempo, asegurate de colocar primero las que son con funciones. De otro modo solo reconocera la de ClassViews y no las de funciones
     # primera vista basada en clases, que sera el detalle de un user

    # path(route='signup/', view=views.signup, name='signup'),    
    path(route='signup/', view=views.SignupView.as_view(), name='signup'),
   
    path(route='<str:username>/',view=views.UserDetailView.as_view(), name='detail'),
    # path(route='<str:username>/',view=TemplateView.as_view(template_name='users/detail.html'), name='detail'),

]

users/models.py
from django.contrib.auth.models import User
from django.db import models


'''Clase que hereda del modelo User'''
class Profile(models.Model):
    # Modelo proxy que extiende los datos base con otra informacion.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username

users/forms.py
# Django
from django import forms

#Models
from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    username=forms.CharField(min_length=4,max_length=50)
    password=forms.CharField(max_length=70, widget=forms.PasswordInput())
    password_confirmation=forms.CharField(max_length=70, widget=forms.PasswordInput())
    first_name=forms.CharField(min_length=2,max_length=50)
    last_name=forms.CharField(min_length=2,max_length=50)
    email=forms.CharField(min_length=6, max_length=70, widget=forms.EmailInput())

    def clean_username(self):
        """Funcion para validar que el nombre del usuario sea unico"""
        username=self.cleaned_data['username'] # Llamamos al dato, que ya fue limpiado con max, y min definidos anteriormente, y validados por djago.
        username_taken=User.objects.filter(username=username).exists() # Con el metod exists() nos devolvera un booleano.
        if username_taken:
            raise forms.ValidationError('El nombre de usuario ya esta en uso') # Con esto lanzamos nuestras propia validacion personalizada y lo mandamos como error.
        return username # Siempre que validez un campo en una funcion tienes que devolver el campo.
    def clean(self):
        """Verificando  que password coincida con password_confirmacion"""
        data =super().clean()# no queremos sobre-escribir todo el metodo que clean manda a llamar a otras cosas, por eso traemos los datos que ya nos traeria clean si no lo hubieramos sobre-escrito
        password=data['password']
        password_confirmation=data['password_confirmation']

        if password!= password_confirmation:
            raise forms.ValidationError('El password no coincide')
        return data
    def save(self):
        """Creacion de usuario y perfil en la DataBase"""
        data=self.cleaned_data # Primero traemos los del form
        data.pop('password_confirmation') # quitamos el dato de password confirmations que nos sirve con el modelo.
        user = User.objects.create_user(**data)
        profile=Profile(user=user)
        profile.save()


class ProfileForm(forms.Form):
    website=forms.URLField(max_length=200, required = True)
    biography=forms.CharField(max_length=500, required =False)
    phone_number=forms.CharField(max_length=20,required=False)
    picture=forms.ImageField()

users/views.py
from django.shortcuts import render,redirect,reverse
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth import views as auth_views

#Exceptions
from django.db.utils import IntegrityError
#Models
from django.contrib.auth.models import User
from users.models import Profile
from posts.models import Post

#Forms
from users.forms import ProfileForm, SignupForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView,FormView,UpdateView

# cuando colocamos un modulo entre parentesis para una nueva clase signifca que la nueva clase heredara todos los metodos

# esta clase devolvera un objeto del tipo que estamos haciendo el queryset
class UserDetailView(DetailView):
    """Vista detallada de usuario"""
    template_name='users/detail.html'
    slug_field='username'  # Nombre de un campo por cual buscar
    slug_url_kwarg='username' # tiene que ser igual al route que pusimos en el path
    queryset=User.objects.all()  # Como su nombre dice, indicamos a partir de que conjunto datos traera los datos.
    context_object_name='user' # Nombre con el que el template recibira los datos. Es como enviarle una varible te tipo diccionario

    # traeremos los posts del usuario encontrado
    def get_context_data(self, **kwargs):
        # agregar a las publicación del usuario al contexto
        context = super().get_context_data(**kwargs)
        user= self.get_object()
        # Agregamos al contexto los datos de los posts de cada usuario y lo ordenamos de manera descendente
        context['posts']= Post.objects.filter(user=user).order_by('-created')
        return context

class SignupView(FormView):
    """Vista para registrar usuarios"""
    template_name='users/signup.html'
    form_class=SignupForm
    success_url=reverse_lazy('users:login')
    def form_valid(self, form):
        form.save() # Recien guardamos en la BD
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin,UpdateView):
    """Vista para actualizar un perfil"""
    template_name='users/update_profile.html'
    model = Profile
    fields=['website','biography','phone_number','picture']
    def get_object(self):
        """Retorna Perfil del usuario"""
        # Especificamos a que modelo hara la actulizacion de los datos,Esto es en el caso de que tengas modelos que deriban de modelos ya definidos en django y que estes usandolos. En este caso como perfil deriba de user, debemos especificar que el modelo a actualizar debe ser profile.
        return self.request.user.profile

    def get_success_url(self):
        """Retorna al perfil del usuario"""
        # Esto nos redireccionara al a vista de detail profile, y como requiere un usermane lo mandamos
        username=self.object.user.username
        return reverse('users:detail', kwargs={'username':username})

class LoginView(auth_views.LoginView):
    """Vista para inision de sesion"""
    template_name='users/login.html'

class LogoutView(LoginRequiredMixin,auth_views.LogoutView):
    """Vista para cerrar sesion"""
    template_name='users/logged_out.html' # Nos inventamos un un nombre de template por que no tenemos un template para esta accion ya que es solo un botton del nav.

"""TODO crear la funcionalidad de like y de follow"""

# @login_required
# def update_profile(request):
#     profile= request.user.profile
#     if request.method =='POST':
#         form = ProfileForm(request.POST,request.FILES)
#         if form.is_valid():
#             data=form.cleaned_data # el metodo cleaned_data nos trae un diccionario con campos ya validados.
#             profile.website=data['website']
#             profile.biography=data['biography']
#             profile.phone_number=data['phone_number']
#             profile.picture = data['picture']
#             profile.save()
#             url=reverse('users:detail',kwargs={'username':request.user.username})
#             return redirect(url)
#     else:
#         form = ProfileForm()   
#     return render(request, 'users/update_profile.html',context=
#         {
#         'profile':profile,
#         'user':request.user,
#         'form': form,
#         }
#     )
    
# def login_view(request):
#     """Login view."""
#     if request.method == 'POST':
#         username = request.POST['username']  # El nombre del campo "username" tiene que igual al name de la input correspondiente del html 
#         password = request.POST['password']

#         user=authenticate(request,username=username,password=password) #Esto verificara si existe un user registrado en nuestra base de datos que coincida con los campos de username y password
#         if user:
#             login(request,user)
#             return redirect('posts:feed')
#         else:
#             return render(request,'users/login.html',{'error':'Usuario y contaseña inválidos'})
#     return render(request, 'users/login.html')

# @login_required
# def logout_view(request):
#     logout(request)
#     return redirect('users:login')


# def signup(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             form.save() # Este metodo lo creamos como una nueva funcion que se encargara de guardarlo en la base de datos
#             return redirect('users:login')
#     else:
#         form= SignupForm()
#     return render(request=request,template_name='users/signup.html',
#     context={'form':form}
#     )

templates/users/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

   {% block head_content %}
   
   {% endblock head_content %}

    {% load static %}
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{%static 'css/main.css' %}" />

</head>
<body class='h-100'>
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
                <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                        <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">
                    {% block container %} {%endblock%}
                </div>
        </div>
    </div>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}
<div class="container mb-5" style="margin-top: 8em;">
    <div class="row">
        <div class="col-sm-4 d-flex justify-content-center">
            <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle"
                width="150px" />
        </div>
        <div class="col-sm-8">
            <h2 style="font-weight: 100;">
                {{ user.username }}
                {% if user == request.user %}
                <a href="{% url "users:update" %}" class="ml-5 btn btn-sm btn-outline-info">
                    Edit profile
                </a>
                {% else %}
                <a href="" class="ml-5 btn btn-sm btn-primary">
                    Follow
                </a>
                {% endif %}
            </h2>
            <div class="row mt-2" style="font-size: 1.2em">
                <div class="col-sm-4">
                    <b>{{ user.profile.posts_count }}785</b> posts
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.followers }}1,401</b> followers
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.following }}491</b> following
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-sm-12">
                    <p>{{ user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
            <div class="col sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:detail' post.pk %}" class="border">
                    <img src="{{post.photo.url }}" alt="{{post.title}}" class="img-fluid">
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}
{% block head_content %}
<title>Platzigram Login</title>
{% endblock head_content %}
{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">'Usuario y contaseña inválidos</p>
    {% endif %}
    <form action="{%url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Usuario</label>
            <input type="text" class="form-control" placeholder="Username" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" class="form-control" placeholder="Password" name="password" id="password">
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
    </form>
    <p class="mt-4">¿Aun no tienes una cuenta? <a href="{% url 'users:signup' %}">Resgistrate aquí</a></p>
{% endblock container %}

templates/users/signup.html
{% extends 'users/base.html' %}
{% block head_content %}
<title>Platzigram sign up</title>
{% endblock head_content %}
{% block container %}

<!-- {% if error %}
    <p class="alert alert-danger">{{error}}</p>
{% endif %} -->

<form method="POST" action="{% url 'users:signup' %}">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary btn-block mt-5" type="submit">Registrar!</button>

</form>
{% endblock container %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">
            <form action="{% url 'users:update'%}" method="POST" enctype="multipart/form-data">
                <!-- la ultima propiedad para el form(enctype) se coloca para que podamos enviar diferentes tipos datos, como archivos, etc. -->
                {% csrf_token %}
                <div class="media">
                    {% if profile.picture %}
                    <img src="{{profile.picture.url}}" class="rounded-circle" height="50">
                    {% else %}
                    <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>
               
                {% for error in form.picture.errors %} 
                <div class="alert alert-danger">
                    <b>Picture:</b><span>{{error}}</span>
               </div> 
               {% endfor %}
            
                <hr>
                <div class="form-group">
                    <label>Website</label>
                    <input 
                    class="form-control {% if form.website.errors %} is-invalid {% endif %}" 
                    type="text"
                        name="website" 
                        placeholder="Website" 
                        value="{% if form.errors %}{{form.website.value}}{% else %}{{profile.website}}{% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                        {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea 
                    class="form-control {% if form.biography.errors %} is-invalid {% endif %}" 
                    name="biography"
                    >{% if form.errors %}{{form.biography.value}}{% else %}{{ profile.biography }}{% endif %}</textarea>
                    <div class="invalid-feedback">
                            {% for error in form.biography.errors %}
                            {{ error }}
                             {% endfor%}
                    </div>
                </div>
                <div class="form-group">
                    <label>Phone number</label>
                    <input 
                    class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}" 
                    type="text" 
                    name="phone_number" placeholder="Phone number"
                    value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{profile.phone_number}}{% endif %}"/>
                    <div class="invalid-feedback">
                            {% for error in form.phone_number.errors %}
                            {{ error }}
                            {% endfor%}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}